# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a new department', max_length=150)),
                ('photo', models.FileField(help_text='Upload a photo', null=True, upload_to='uploads/item/photos/')),
            ],
        ),
    ]
