# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(help_text='Enter email id to be searched', max_length=200)),
                ('department', models.ForeignKey(help_text='Enter your department', on_delete=django.db.models.deletion.CASCADE, to='profiles.Department')),
                ('user', models.OneToOneField(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
