# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category', max_length=100)),
                ('search_text', models.CharField(help_text='Search keyword for crawling mail', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='Enter data', max_length=10000)),
                ('category', models.ForeignKey(help_text='Enter category data', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='profiles.Category')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='mail_password',
            field=models.CharField(blank=True, help_text='Enter your password', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.ImageField(default='default_pic.jpg', help_text='Upload your profile picture', upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='mail',
            field=models.CharField(blank=True, help_text='Enter email id to be searched', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='professor',
            field=models.ForeignKey(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='profiles.Professor'),
        ),
    ]
