# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171111_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='professor',
            field=models.ForeignKey(help_text='a', on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='category',
            field=models.ForeignKey(help_text='Enter category data', on_delete=django.db.models.deletion.CASCADE, to='profiles.Category'),
        ),
    ]
