# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171113_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, help_text='Enter your degree', max_length=200, null=True)),
                ('description', models.CharField(blank=True, help_text='Enter degree description', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, help_text='Enter your degree', max_length=200, null=True)),
                ('description', models.CharField(blank=True, help_text='Enter degree description', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='phone_home',
            field=models.CharField(blank=True, help_text='Enter your home phone no.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone_office',
            field=models.CharField(blank=True, help_text='Enter your office phone no.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='post',
            field=models.CharField(blank=True, help_text='Enter your post', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='qtr_no',
            field=models.CharField(blank=True, help_text='Enter your qtr no.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='room_no',
            field=models.CharField(blank=True, help_text='Enter your room no.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='professor',
            field=models.OneToOneField(help_text='b', on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AddField(
            model_name='education',
            name='professor',
            field=models.OneToOneField(help_text='b', on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
    ]
