# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20171114_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='professor',
            field=models.ForeignKey(help_text='b', on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AlterField(
            model_name='work',
            name='professor',
            field=models.ForeignKey(help_text='b', on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
    ]
