# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171114_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='to_crawl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='search_text',
            field=models.CharField(blank=True, help_text='Search keyword for crawling mail', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(default='default_pic.png', help_text='Upload your profile picture', upload_to='uploads/photos/'),
        ),
    ]
