# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20171114_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='to_crawl',
            field=models.BooleanField(default=False, help_text='Enable/Disable webmail crawling for this category'),
        ),
    ]
