# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20171115_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='mail_server',
            field=models.CharField(blank=True, choices=[('te', 'Teesta'), ('n', 'Naambor'), ('d', 'Disang'), ('ta', 'Tamdil'), ('di', 'Dikrong')], default='te', help_text='Select your webmail server', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, help_text='Enter Post description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='post',
            field=models.CharField(blank=True, help_text='Enter your Post', max_length=200, null=True),
        ),
    ]
