# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20171116_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='to_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='mail',
            field=models.CharField(blank=True, help_text='@iitg.ernet.in', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='mail_server',
            field=models.CharField(blank=True, choices=[('0', 'Teesta'), ('1', 'Naambor'), ('2', 'Disang'), ('3', 'Tamdil'), ('4', 'Dikrong')], default='te', help_text='Select your webmail server', max_length=2, null=True),
        ),
    ]
