# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20171116_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylist',
            name='to_approve',
        ),
        migrations.AddField(
            model_name='categorylist',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
