# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20171116_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='search_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='temp_post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
