# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20171116_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, default='default_pic.png', help_text='Upload your profile picture', null=True, upload_to='uploads/photos/'),
        ),
    ]
